MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.14"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.14"                # [osx and x86_64]
CONDA_BUILD_SYSROOT:       # [osx and x86_64]
  - /opt/MacOSX10.14.sdk   # [osx and x86_64]
suffix:
  - ""
  - "-novec"
cxx_compiler:              # [win]
- vs2019                   # [win]
c_compiler:                # [win]
- vs2019                   # [win]